### ISSUE TITLE
Looks nice!

### ISSUE THREAD

**Issue by SebastianRoll** [jgaz/sensorizer#13]
A few quick comments:

- I couldn't find requirements.txt anywhere
- abc abstractmethod is useful if you want to enforce QueueInterface methods
- I didn't look closely at the counter attribute, but might be worthwhile to look into class variables vs object variables

Keep on truckin'!

**Comment by jgaz** [comment]
Hi there, thank you for the feedback! 
The requirements are in the setup.cfg, I am trying to pack as much there as possible to avoid some files lying around.
I will look into the abc, I have seen it used from time to time, but probably the queue interface is where the library could grow in the near future so it makes sense to be more "strict" there.
And about the counter, to me looks definitely a class variable, I want to be able to check if what lands on the data sink is what it has been sent, I just changed the declaration as object variable, well spotted :)

**Comment by SebastianRoll** [comment]
I haven't put deps in setup.cfg before, but I can see it's done [here](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files). Will consider this for my next project :)
